### ISSUE TITLE
Large pic breaks FancyBox

### ISSUE THREAD

**Issue by jimzhan** [hexojs/hexo-theme-phase#1]
![FancyBox](http://i1.minus.com/jbbZjOVNeYGYNO.png)

**Comment by curbengh** [comment]
> 如何让gallery几秒钟自动切换下一张

Modify the following line:
https://github.com/hexojs/hexo-theme-phase/blob/97bae5e939014417becd26d306ae30a7d9e189a7/layout/_partial/after_footer.ejs#L23

``` js
$('.fancybox').fancybox({
  slideShow: {
    autoStart: true,
    speed: 3000
  }
});

[More options](https://fancyapps.com/fancybox/3/docs/#options)
